### ISSUE TITLE
Policy page

### ISSUE THREAD

**Issue by noni-12** [ConclusionNL/global-mitigation-potential-atlas#127]
Update the settings for marking the start year of the climate strategy and policy inventory page, so that it can be alpha-numerical format

![Screenshot 2023-11-27 at 10 12 42 am](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/150308465/a490b693-ac3a-4a23-94cd-0a73fed73489)
![Screenshot 2023-11-27 at 10 15 52 am](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/150308465/8ddcf4f8-47d0-407a-96a1-7258f70b489f)

**Comment by noni-12** [comment]
Please also update the "valid till" in similar manner

**Comment by lucasjellema** [comment]
@noni-12  I hope this description is enough for @Quintin-Yu  to implement your requirement. For me it is not clear what exactly you want to have implemented.

**Comment by Quintin-Yu** [comment]
![image](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/36072659/a8d34923-7645-40f3-b6eb-98e2a91b58be)
![image](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/36072659/b933dffb-7a5d-4a12-b9d5-e8bf6c6aac4c)
Has now been implemented on the accept as no code changes were needed

**Comment by noni-12** [comment]
It's not working for start year. If I write text after number then it's showing as 0 in the web tool.
For valid till, if I don't add anything its showing as ongoing - that's  okay for us.
![Screenshot 2023-11-27 at 4 42 49 pm](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/150308465/6180c392-1f08-4863-b726-56c279a847d5)

**Comment by Quintin-Yu** [comment]
There was a code change needed. It should now be working as intended. @noni-12

**Comment by Quintin-Yu** [comment]
![image](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/36072659/4f0970a5-9b13-41fc-be52-28970da9c24c)
Ongoing is added back as requested in #128 

For future comments please keep them to the related issues

**Comment by noni-12** [comment]
Apology for mixing up issues

Valid till as 'on going' is still not working
![Screenshot 2023-11-27 at 6 32 02 pm](https://github.com/ConclusionNL/global-mitigation-potential-atlas/assets/150308465/b64fd3a9-9a3e-4cd5-8276-90b6cac6c901)

**Comment by Quintin-Yu** [comment]
Please check the test environment. That's where the change is active

**Comment by noni-12** [comment]
Perfect, thanks
